// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication2.Data;

namespace WebApplication2.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20201114114729_Cmpg3232DataImported")]
    partial class Cmpg3232DataImported
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApplication2.Data.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BusinessTravel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DailyRate")
                        .HasColumnType("int");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DistanceFromHome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Education")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EducationField")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeCount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnvironmentSatisfaction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HourlyRate")
                        .HasColumnType("int");

                    b.Property<string>("JobInvolvement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobRole")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobSatisfaction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaritalStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MonthlyIncome")
                        .HasColumnType("int");

                    b.Property<int>("MonthlyRate")
                        .HasColumnType("int");

                    b.Property<string>("NumCompaniesWorked")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Over18")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OverTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PercentSalaryHike")
                        .HasColumnType("int");

                    b.Property<int>("PerformanceRating")
                        .HasColumnType("int");

                    b.Property<string>("RelationshipSatisfaction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StandardHours")
                        .HasColumnType("int");

                    b.Property<string>("StockOptionLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TotalWorkingYears")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrainingTimesLastYear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkLifeBalance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YearsAtCompany")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YearsInCurrentRole")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YearsSinceLastPromotion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YearsWithCurrManager")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.Property<string>("attrition")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CMPG323project2dataset");
                });
#pragma warning restore 612, 618
        }
    }
}
